export default [
  {
    label: "Afghanistan",
    value: "Afghanistan",
    code: "AF",
    "alpha-2": "AF",
    "alpha-3": "AFG",
    "country-code": "004",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Åland Islands",
    value: "Åland Islands",
    code: "AX",
    "alpha-2": "AX",
    "alpha-3": "ALA",
    "country-code": "248",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Albania",
    value: "Albania",
    code: "AL",
    "alpha-2": "AL",
    "alpha-3": "ALB",
    "country-code": "008",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Algeria",
    value: "Algeria",
    code: "DZ",
    "alpha-2": "DZ",
    "alpha-3": "DZA",
    "country-code": "012",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "American Samoa",
    value: "American Samoa",
    code: "AS",
    "alpha-2": "AS",
    "alpha-3": "ASM",
    "country-code": "016",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Andorra",
    value: "Andorra",
    code: "AD",
    "alpha-2": "AD",
    "alpha-3": "AND",
    "country-code": "020",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Angola",
    value: "Angola",
    code: "AO",
    "alpha-2": "AO",
    "alpha-3": "AGO",
    "country-code": "024",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Anguilla",
    value: "Anguilla",
    code: "AI",
    "alpha-2": "AI",
    "alpha-3": "AIA",
    "country-code": "660",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Antarctica",
    value: "Antarctica",
    code: "AQ",
    "alpha-2": "AQ",
    "alpha-3": "ATA",
    "country-code": "010",
    region: "",
    "sub-region": "",
    "region-code": "",
    "sub-region-code": "",
  },
  {
    label: "Antigua and Barbuda",
    value: "Antigua and Barbuda",
    code: "AG",
    "alpha-2": "AG",
    "alpha-3": "ATG",
    "country-code": "028",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Argentina",
    value: "Argentina",
    code: "AR",
    "alpha-2": "AR",
    "alpha-3": "ARG",
    "country-code": "032",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Armenia",
    value: "Armenia",
    code: "AM",
    "alpha-2": "AM",
    "alpha-3": "ARM",
    "country-code": "051",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Aruba",
    value: "Aruba",
    code: "AW",
    "alpha-2": "AW",
    "alpha-3": "ABW",
    "country-code": "533",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Australia",
    value: "Australia",
    code: "AU",
    "alpha-2": "AU",
    "alpha-3": "AUS",
    "country-code": "036",
    region: "Oceania",
    "sub-region": "Australia and New Zealand",
    "region-code": "009",
    "sub-region-code": "053",
  },
  {
    label: "Austria",
    value: "Austria",
    code: "AT",
    "alpha-2": "AT",
    "alpha-3": "AUT",
    "country-code": "040",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Azerbaijan",
    value: "Azerbaijan",
    code: "AZ",
    "alpha-2": "AZ",
    "alpha-3": "AZE",
    "country-code": "031",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Bahamas",
    value: "Bahamas",
    code: "BS",
    "alpha-2": "BS",
    "alpha-3": "BHS",
    "country-code": "044",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Bahrain",
    value: "Bahrain",
    code: "BH",
    "alpha-2": "BH",
    "alpha-3": "BHR",
    "country-code": "048",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Bangladesh",
    value: "Bangladesh",
    code: "BD",
    "alpha-2": "BD",
    "alpha-3": "BGD",
    "country-code": "050",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Barbados",
    value: "Barbados",
    code: "BB",
    "alpha-2": "BB",
    "alpha-3": "BRB",
    "country-code": "052",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Belarus",
    value: "Belarus",
    code: "BY",
    "alpha-2": "BY",
    "alpha-3": "BLR",
    "country-code": "112",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Belgium",
    value: "Belgium",
    code: "BE",
    "alpha-2": "BE",
    "alpha-3": "BEL",
    "country-code": "056",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Belize",
    value: "Belize",
    code: "BZ",
    "alpha-2": "BZ",
    "alpha-3": "BLZ",
    "country-code": "084",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Benin",
    value: "Benin",
    code: "BJ",
    "alpha-2": "BJ",
    "alpha-3": "BEN",
    "country-code": "204",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Bermuda",
    value: "Bermuda",
    code: "BM",
    "alpha-2": "BM",
    "alpha-3": "BMU",
    "country-code": "060",
    region: "Americas",
    "sub-region": "Northern America",
    "region-code": "019",
    "sub-region-code": "021",
  },
  {
    label: "Bhutan",
    value: "Bhutan",
    code: "BT",
    "alpha-2": "BT",
    "alpha-3": "BTN",
    "country-code": "064",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Bolivia (Plurinational State of)",
    value: "Bolivia (Plurinational State of)",
    code: "BO",
    "alpha-2": "BO",
    "alpha-3": "BOL",
    "country-code": "068",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Bonaire, Sint Eustatius and Saba",
    value: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    "alpha-2": "BQ",
    "alpha-3": "BES",
    "country-code": "535",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Bosnia and Herzegovina",
    value: "Bosnia and Herzegovina",
    code: "BA",
    "alpha-2": "BA",
    "alpha-3": "BIH",
    "country-code": "070",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Botswana",
    value: "Botswana",
    code: "BW",
    "alpha-2": "BW",
    "alpha-3": "BWA",
    "country-code": "072",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Bouvet Island",
    value: "Bouvet Island",
    code: "BV",
    "alpha-2": "BV",
    "alpha-3": "BVT",
    "country-code": "074",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Brazil",
    value: "Brazil",
    code: "BR",
    "alpha-2": "BR",
    "alpha-3": "BRA",
    "country-code": "076",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "British Indian Ocean Territory",
    value: "British Indian Ocean Territory",
    code: "IO",
    "alpha-2": "IO",
    "alpha-3": "IOT",
    "country-code": "086",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Brunei Darussalam",
    value: "Brunei Darussalam",
    code: "BN",
    "alpha-2": "BN",
    "alpha-3": "BRN",
    "country-code": "096",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Bulgaria",
    value: "Bulgaria",
    code: "BG",
    "alpha-2": "BG",
    "alpha-3": "BGR",
    "country-code": "100",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Burkina Faso",
    value: "Burkina Faso",
    code: "BF",
    "alpha-2": "BF",
    "alpha-3": "BFA",
    "country-code": "854",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Burundi",
    value: "Burundi",
    code: "BI",
    "alpha-2": "BI",
    "alpha-3": "BDI",
    "country-code": "108",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Cabo Verde",
    value: "Cabo Verde",
    code: "CV",
    "alpha-2": "CV",
    "alpha-3": "CPV",
    "country-code": "132",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Cambodia",
    value: "Cambodia",
    code: "KH",
    "alpha-2": "KH",
    "alpha-3": "KHM",
    "country-code": "116",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Cameroon",
    value: "Cameroon",
    code: "CM",
    "alpha-2": "CM",
    "alpha-3": "CMR",
    "country-code": "120",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Canada",
    value: "Canada",
    code: "CA",
    "alpha-2": "CA",
    "alpha-3": "CAN",
    "country-code": "124",
    region: "Americas",
    "sub-region": "Northern America",
    "region-code": "019",
    "sub-region-code": "021",
  },
  {
    label: "Cayman Islands",
    value: "Cayman Islands",
    code: "KY",
    "alpha-2": "KY",
    "alpha-3": "CYM",
    "country-code": "136",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Central African Republic",
    value: "Central African Republic",
    code: "CF",
    "alpha-2": "CF",
    "alpha-3": "CAF",
    "country-code": "140",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Chad",
    value: "Chad",
    code: "TD",
    "alpha-2": "TD",
    "alpha-3": "TCD",
    "country-code": "148",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Chile",
    value: "Chile",
    code: "CL",
    "alpha-2": "CL",
    "alpha-3": "CHL",
    "country-code": "152",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "China",
    value: "China",
    code: "CN",
    "alpha-2": "CN",
    "alpha-3": "CHN",
    "country-code": "156",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Christmas Island",
    value: "Christmas Island",
    code: "CX",
    "alpha-2": "CX",
    "alpha-3": "CXR",
    "country-code": "162",
    region: "Oceania",
    "sub-region": "Australia and New Zealand",
    "region-code": "009",
    "sub-region-code": "053",
  },
  {
    label: "Cocos (Keeling) Islands",
    value: "Cocos (Keeling) Islands",
    code: "CC",
    "alpha-2": "CC",
    "alpha-3": "CCK",
    "country-code": "166",
    region: "Oceania",
    "sub-region": "Australia and New Zealand",
    "region-code": "009",
    "sub-region-code": "053",
  },
  {
    label: "Colombia",
    value: "Colombia",
    code: "CO",
    "alpha-2": "CO",
    "alpha-3": "COL",
    "country-code": "170",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Comoros",
    value: "Comoros",
    code: "KM",
    "alpha-2": "KM",
    "alpha-3": "COM",
    "country-code": "174",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Congo",
    value: "Congo",
    code: "CG",
    "alpha-2": "CG",
    "alpha-3": "COG",
    "country-code": "178",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Congo, Democratic Republic of the",
    value: "Congo, Democratic Republic of the",
    code: "CD",
    "alpha-2": "CD",
    "alpha-3": "COD",
    "country-code": "180",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Cook Islands",
    value: "Cook Islands",
    code: "CK",
    "alpha-2": "CK",
    "alpha-3": "COK",
    "country-code": "184",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Costa Rica",
    value: "Costa Rica",
    code: "CR",
    "alpha-2": "CR",
    "alpha-3": "CRI",
    "country-code": "188",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Côte d'Ivoire",
    value: "Côte d'Ivoire",
    code: "CI",
    "alpha-2": "CI",
    "alpha-3": "CIV",
    "country-code": "384",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Croatia",
    value: "Croatia",
    code: "HR",
    "alpha-2": "HR",
    "alpha-3": "HRV",
    "country-code": "191",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Cuba",
    value: "Cuba",
    code: "CU",
    "alpha-2": "CU",
    "alpha-3": "CUB",
    "country-code": "192",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Curaçao",
    value: "Curaçao",
    code: "CW",
    "alpha-2": "CW",
    "alpha-3": "CUW",
    "country-code": "531",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Cyprus",
    value: "Cyprus",
    code: "CY",
    "alpha-2": "CY",
    "alpha-3": "CYP",
    "country-code": "196",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Czechia",
    value: "Czechia",
    code: "CZ",
    "alpha-2": "CZ",
    "alpha-3": "CZE",
    "country-code": "203",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Denmark",
    value: "Denmark",
    code: "DK",
    "alpha-2": "DK",
    "alpha-3": "DNK",
    "country-code": "208",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Djibouti",
    value: "Djibouti",
    code: "DJ",
    "alpha-2": "DJ",
    "alpha-3": "DJI",
    "country-code": "262",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Dominica",
    value: "Dominica",
    code: "DM",
    "alpha-2": "DM",
    "alpha-3": "DMA",
    "country-code": "212",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Dominican Republic",
    value: "Dominican Republic",
    code: "DO",
    "alpha-2": "DO",
    "alpha-3": "DOM",
    "country-code": "214",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Ecuador",
    value: "Ecuador",
    code: "EC",
    "alpha-2": "EC",
    "alpha-3": "ECU",
    "country-code": "218",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Egypt",
    value: "Egypt",
    code: "EG",
    "alpha-2": "EG",
    "alpha-3": "EGY",
    "country-code": "818",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "El Salvador",
    value: "El Salvador",
    code: "SV",
    "alpha-2": "SV",
    "alpha-3": "SLV",
    "country-code": "222",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Equatorial Guinea",
    value: "Equatorial Guinea",
    code: "GQ",
    "alpha-2": "GQ",
    "alpha-3": "GNQ",
    "country-code": "226",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Eritrea",
    value: "Eritrea",
    code: "ER",
    "alpha-2": "ER",
    "alpha-3": "ERI",
    "country-code": "232",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Estonia",
    value: "Estonia",
    code: "EE",
    "alpha-2": "EE",
    "alpha-3": "EST",
    "country-code": "233",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Eswatini",
    value: "Eswatini",
    code: "SZ",
    "alpha-2": "SZ",
    "alpha-3": "SWZ",
    "country-code": "748",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Ethiopia",
    value: "Ethiopia",
    code: "ET",
    "alpha-2": "ET",
    "alpha-3": "ETH",
    "country-code": "231",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Falkland Islands (Malvinas)",
    value: "Falkland Islands (Malvinas)",
    code: "FK",
    "alpha-2": "FK",
    "alpha-3": "FLK",
    "country-code": "238",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Faroe Islands",
    value: "Faroe Islands",
    code: "FO",
    "alpha-2": "FO",
    "alpha-3": "FRO",
    "country-code": "234",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Fiji",
    value: "Fiji",
    code: "FJ",
    "alpha-2": "FJ",
    "alpha-3": "FJI",
    "country-code": "242",
    region: "Oceania",
    "sub-region": "Melanesia",
    "region-code": "009",
    "sub-region-code": "054",
  },
  {
    label: "Finland",
    value: "Finland",
    code: "FI",
    "alpha-2": "FI",
    "alpha-3": "FIN",
    "country-code": "246",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "France",
    value: "France",
    code: "FR",
    "alpha-2": "FR",
    "alpha-3": "FRA",
    "country-code": "250",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "French Guiana",
    value: "French Guiana",
    code: "GF",
    "alpha-2": "GF",
    "alpha-3": "GUF",
    "country-code": "254",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "French Polynesia",
    value: "French Polynesia",
    code: "PF",
    "alpha-2": "PF",
    "alpha-3": "PYF",
    "country-code": "258",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "French Southern Territories",
    value: "French Southern Territories",
    code: "TF",
    "alpha-2": "TF",
    "alpha-3": "ATF",
    "country-code": "260",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Gabon",
    value: "Gabon",
    code: "GA",
    "alpha-2": "GA",
    "alpha-3": "GAB",
    "country-code": "266",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Gambia",
    value: "Gambia",
    code: "GM",
    "alpha-2": "GM",
    "alpha-3": "GMB",
    "country-code": "270",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Georgia",
    value: "Georgia",
    code: "GE",
    "alpha-2": "GE",
    "alpha-3": "GEO",
    "country-code": "268",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Germany",
    value: "Germany",
    code: "DE",
    "alpha-2": "DE",
    "alpha-3": "DEU",
    "country-code": "276",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Ghana",
    value: "Ghana",
    code: "GH",
    "alpha-2": "GH",
    "alpha-3": "GHA",
    "country-code": "288",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Gibraltar",
    value: "Gibraltar",
    code: "GI",
    "alpha-2": "GI",
    "alpha-3": "GIB",
    "country-code": "292",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Greece",
    value: "Greece",
    code: "GR",
    "alpha-2": "GR",
    "alpha-3": "GRC",
    "country-code": "300",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Greenland",
    value: "Greenland",
    code: "GL",
    "alpha-2": "GL",
    "alpha-3": "GRL",
    "country-code": "304",
    region: "Americas",
    "sub-region": "Northern America",
    "region-code": "019",
    "sub-region-code": "021",
  },
  {
    label: "Grenada",
    value: "Grenada",
    code: "GD",
    "alpha-2": "GD",
    "alpha-3": "GRD",
    "country-code": "308",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Guadeloupe",
    value: "Guadeloupe",
    code: "GP",
    "alpha-2": "GP",
    "alpha-3": "GLP",
    "country-code": "312",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Guam",
    value: "Guam",
    code: "GU",
    "alpha-2": "GU",
    "alpha-3": "GUM",
    "country-code": "316",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Guatemala",
    value: "Guatemala",
    code: "GT",
    "alpha-2": "GT",
    "alpha-3": "GTM",
    "country-code": "320",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Guernsey",
    value: "Guernsey",
    code: "GG",
    "alpha-2": "GG",
    "alpha-3": "GGY",
    "country-code": "831",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Guinea",
    value: "Guinea",
    code: "GN",
    "alpha-2": "GN",
    "alpha-3": "GIN",
    "country-code": "324",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Guinea-Bissau",
    value: "Guinea-Bissau",
    code: "GW",
    "alpha-2": "GW",
    "alpha-3": "GNB",
    "country-code": "624",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Guyana",
    value: "Guyana",
    code: "GY",
    "alpha-2": "GY",
    "alpha-3": "GUY",
    "country-code": "328",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Haiti",
    value: "Haiti",
    code: "HT",
    "alpha-2": "HT",
    "alpha-3": "HTI",
    "country-code": "332",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Heard Island and McDonald Islands",
    value: "Heard Island and McDonald Islands",
    code: "HM",
    "alpha-2": "HM",
    "alpha-3": "HMD",
    "country-code": "334",
    region: "Oceania",
    "sub-region": "Australia and New Zealand",
    "region-code": "009",
    "sub-region-code": "053",
  },
  {
    label: "Holy See",
    value: "Holy See",
    code: "VA",
    "alpha-2": "VA",
    "alpha-3": "VAT",
    "country-code": "336",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Honduras",
    value: "Honduras",
    code: "HN",
    "alpha-2": "HN",
    "alpha-3": "HND",
    "country-code": "340",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Hong Kong",
    value: "Hong Kong",
    code: "HK",
    "alpha-2": "HK",
    "alpha-3": "HKG",
    "country-code": "344",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Hungary",
    value: "Hungary",
    code: "HU",
    "alpha-2": "HU",
    "alpha-3": "HUN",
    "country-code": "348",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Iceland",
    value: "Iceland",
    code: "IS",
    "alpha-2": "IS",
    "alpha-3": "ISL",
    "country-code": "352",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "India",
    value: "India",
    code: "IN",
    "alpha-2": "IN",
    "alpha-3": "IND",
    "country-code": "356",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Indonesia",
    value: "Indonesia",
    code: "ID",
    "alpha-2": "ID",
    "alpha-3": "IDN",
    "country-code": "360",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Iran (Islamic Republic of)",
    value: "Iran (Islamic Republic of)",
    code: "IR",
    "alpha-2": "IR",
    "alpha-3": "IRN",
    "country-code": "364",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Iraq",
    value: "Iraq",
    code: "IQ",
    "alpha-2": "IQ",
    "alpha-3": "IRQ",
    "country-code": "368",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Ireland",
    value: "Ireland",
    code: "IE",
    "alpha-2": "IE",
    "alpha-3": "IRL",
    "country-code": "372",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Isle of Man",
    value: "Isle of Man",
    code: "IM",
    "alpha-2": "IM",
    "alpha-3": "IMN",
    "country-code": "833",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Israel",
    value: "Israel",
    code: "IL",
    "alpha-2": "IL",
    "alpha-3": "ISR",
    "country-code": "376",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Italy",
    value: "Italy",
    code: "IT",
    "alpha-2": "IT",
    "alpha-3": "ITA",
    "country-code": "380",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Jamaica",
    value: "Jamaica",
    code: "JM",
    "alpha-2": "JM",
    "alpha-3": "JAM",
    "country-code": "388",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Japan",
    value: "Japan",
    code: "JP",
    "alpha-2": "JP",
    "alpha-3": "JPN",
    "country-code": "392",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Jersey",
    value: "Jersey",
    code: "JE",
    "alpha-2": "JE",
    "alpha-3": "JEY",
    "country-code": "832",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Jordan",
    value: "Jordan",
    code: "JO",
    "alpha-2": "JO",
    "alpha-3": "JOR",
    "country-code": "400",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Kazakhstan",
    value: "Kazakhstan",
    code: "KZ",
    "alpha-2": "KZ",
    "alpha-3": "KAZ",
    "country-code": "398",
    region: "Asia",
    "sub-region": "Central Asia",
    "region-code": "142",
    "sub-region-code": "143",
  },
  {
    label: "Kenya",
    value: "Kenya",
    code: "KE",
    "alpha-2": "KE",
    "alpha-3": "KEN",
    "country-code": "404",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Kiribati",
    value: "Kiribati",
    code: "KI",
    "alpha-2": "KI",
    "alpha-3": "KIR",
    "country-code": "296",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Korea (Democratic People's Republic of)",
    value: "Korea (Democratic People's Republic of)",
    code: "KP",
    "alpha-2": "KP",
    "alpha-3": "PRK",
    "country-code": "408",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Korea, Republic of",
    value: "Korea, Republic of",
    code: "KR",
    "alpha-2": "KR",
    "alpha-3": "KOR",
    "country-code": "410",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Kuwait",
    value: "Kuwait",
    code: "KW",
    "alpha-2": "KW",
    "alpha-3": "KWT",
    "country-code": "414",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Kyrgyzstan",
    value: "Kyrgyzstan",
    code: "KG",
    "alpha-2": "KG",
    "alpha-3": "KGZ",
    "country-code": "417",
    region: "Asia",
    "sub-region": "Central Asia",
    "region-code": "142",
    "sub-region-code": "143",
  },
  {
    label: "Lao People's Democratic Republic",
    value: "Lao People's Democratic Republic",
    code: "LA",
    "alpha-2": "LA",
    "alpha-3": "LAO",
    "country-code": "418",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Latvia",
    value: "Latvia",
    code: "LV",
    "alpha-2": "LV",
    "alpha-3": "LVA",
    "country-code": "428",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Lebanon",
    value: "Lebanon",
    code: "LB",
    "alpha-2": "LB",
    "alpha-3": "LBN",
    "country-code": "422",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Lesotho",
    value: "Lesotho",
    code: "LS",
    "alpha-2": "LS",
    "alpha-3": "LSO",
    "country-code": "426",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Liberia",
    value: "Liberia",
    code: "LR",
    "alpha-2": "LR",
    "alpha-3": "LBR",
    "country-code": "430",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Libya",
    value: "Libya",
    code: "LY",
    "alpha-2": "LY",
    "alpha-3": "LBY",
    "country-code": "434",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "Liechtenstein",
    value: "Liechtenstein",
    code: "LI",
    "alpha-2": "LI",
    "alpha-3": "LIE",
    "country-code": "438",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Lithuania",
    value: "Lithuania",
    code: "LT",
    "alpha-2": "LT",
    "alpha-3": "LTU",
    "country-code": "440",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Luxembourg",
    value: "Luxembourg",
    code: "LU",
    "alpha-2": "LU",
    "alpha-3": "LUX",
    "country-code": "442",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Macao",
    value: "Macao",
    code: "MO",
    "alpha-2": "MO",
    "alpha-3": "MAC",
    "country-code": "446",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Madagascar",
    value: "Madagascar",
    code: "MG",
    "alpha-2": "MG",
    "alpha-3": "MDG",
    "country-code": "450",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Malawi",
    value: "Malawi",
    code: "MW",
    "alpha-2": "MW",
    "alpha-3": "MWI",
    "country-code": "454",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Malaysia",
    value: "Malaysia",
    code: "MY",
    "alpha-2": "MY",
    "alpha-3": "MYS",
    "country-code": "458",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Maldives",
    value: "Maldives",
    code: "MV",
    "alpha-2": "MV",
    "alpha-3": "MDV",
    "country-code": "462",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Mali",
    value: "Mali",
    code: "ML",
    "alpha-2": "ML",
    "alpha-3": "MLI",
    "country-code": "466",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Malta",
    value: "Malta",
    code: "MT",
    "alpha-2": "MT",
    "alpha-3": "MLT",
    "country-code": "470",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Marshall Islands",
    value: "Marshall Islands",
    code: "MH",
    "alpha-2": "MH",
    "alpha-3": "MHL",
    "country-code": "584",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Martinique",
    value: "Martinique",
    code: "MQ",
    "alpha-2": "MQ",
    "alpha-3": "MTQ",
    "country-code": "474",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Mauritania",
    value: "Mauritania",
    code: "MR",
    "alpha-2": "MR",
    "alpha-3": "MRT",
    "country-code": "478",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Mauritius",
    value: "Mauritius",
    code: "MU",
    "alpha-2": "MU",
    "alpha-3": "MUS",
    "country-code": "480",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Mayotte",
    value: "Mayotte",
    code: "YT",
    "alpha-2": "YT",
    "alpha-3": "MYT",
    "country-code": "175",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Mexico",
    value: "Mexico",
    code: "MX",
    "alpha-2": "MX",
    "alpha-3": "MEX",
    "country-code": "484",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Micronesia (Federated States of)",
    value: "Micronesia (Federated States of)",
    code: "FM",
    "alpha-2": "FM",
    "alpha-3": "FSM",
    "country-code": "583",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Moldova, Republic of",
    value: "Moldova, Republic of",
    code: "MD",
    "alpha-2": "MD",
    "alpha-3": "MDA",
    "country-code": "498",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Monaco",
    value: "Monaco",
    code: "MC",
    "alpha-2": "MC",
    "alpha-3": "MCO",
    "country-code": "492",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Mongolia",
    value: "Mongolia",
    code: "MN",
    "alpha-2": "MN",
    "alpha-3": "MNG",
    "country-code": "496",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Montenegro",
    value: "Montenegro",
    code: "ME",
    "alpha-2": "ME",
    "alpha-3": "MNE",
    "country-code": "499",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Montserrat",
    value: "Montserrat",
    code: "MS",
    "alpha-2": "MS",
    "alpha-3": "MSR",
    "country-code": "500",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Morocco",
    value: "Morocco",
    code: "MA",
    "alpha-2": "MA",
    "alpha-3": "MAR",
    "country-code": "504",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "Mozambique",
    value: "Mozambique",
    code: "MZ",
    "alpha-2": "MZ",
    "alpha-3": "MOZ",
    "country-code": "508",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Myanmar",
    value: "Myanmar",
    code: "MM",
    "alpha-2": "MM",
    "alpha-3": "MMR",
    "country-code": "104",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Namibia",
    value: "Namibia",
    code: "NA",
    "alpha-2": "NA",
    "alpha-3": "NAM",
    "country-code": "516",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Nauru",
    value: "Nauru",
    code: "NR",
    "alpha-2": "NR",
    "alpha-3": "NRU",
    "country-code": "520",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Nepal",
    value: "Nepal",
    code: "NP",
    "alpha-2": "NP",
    "alpha-3": "NPL",
    "country-code": "524",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Netherlands",
    value: "Netherlands",
    code: "NL",
    "alpha-2": "NL",
    "alpha-3": "NLD",
    "country-code": "528",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "New Caledonia",
    value: "New Caledonia",
    code: "NC",
    "alpha-2": "NC",
    "alpha-3": "NCL",
    "country-code": "540",
    region: "Oceania",
    "sub-region": "Melanesia",
    "region-code": "009",
    "sub-region-code": "054",
  },
  {
    label: "New Zealand",
    value: "New Zealand",
    code: "NZ",
    "alpha-2": "NZ",
    "alpha-3": "NZL",
    "country-code": "554",
    region: "Oceania",
    "sub-region": "Australia and New Zealand",
    "region-code": "009",
    "sub-region-code": "053",
  },
  {
    label: "Nicaragua",
    value: "Nicaragua",
    code: "NI",
    "alpha-2": "NI",
    "alpha-3": "NIC",
    "country-code": "558",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Niger",
    value: "Niger",
    code: "NE",
    "alpha-2": "NE",
    "alpha-3": "NER",
    "country-code": "562",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Nigeria",
    value: "Nigeria",
    code: "NG",
    "alpha-2": "NG",
    "alpha-3": "NGA",
    "country-code": "566",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Niue",
    value: "Niue",
    code: "NU",
    "alpha-2": "NU",
    "alpha-3": "NIU",
    "country-code": "570",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Norfolk Island",
    value: "Norfolk Island",
    code: "NF",
    "alpha-2": "NF",
    "alpha-3": "NFK",
    "country-code": "574",
    region: "Oceania",
    "sub-region": "Australia and New Zealand",
    "region-code": "009",
    "sub-region-code": "053",
  },
  {
    label: "North Macedonia",
    value: "North Macedonia",
    code: "MK",
    "alpha-2": "MK",
    "alpha-3": "MKD",
    "country-code": "807",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Northern Mariana Islands",
    value: "Northern Mariana Islands",
    code: "MP",
    "alpha-2": "MP",
    "alpha-3": "MNP",
    "country-code": "580",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Norway",
    value: "Norway",
    code: "NO",
    "alpha-2": "NO",
    "alpha-3": "NOR",
    "country-code": "578",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Oman",
    value: "Oman",
    code: "OM",
    "alpha-2": "OM",
    "alpha-3": "OMN",
    "country-code": "512",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Pakistan",
    value: "Pakistan",
    code: "PK",
    "alpha-2": "PK",
    "alpha-3": "PAK",
    "country-code": "586",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Palau",
    value: "Palau",
    code: "PW",
    "alpha-2": "PW",
    "alpha-3": "PLW",
    "country-code": "585",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Palestine, State of",
    value: "Palestine, State of",
    code: "PS",
    "alpha-2": "PS",
    "alpha-3": "PSE",
    "country-code": "275",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Panama",
    value: "Panama",
    code: "PA",
    "alpha-2": "PA",
    "alpha-3": "PAN",
    "country-code": "591",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Papua New Guinea",
    value: "Papua New Guinea",
    code: "PG",
    "alpha-2": "PG",
    "alpha-3": "PNG",
    "country-code": "598",
    region: "Oceania",
    "sub-region": "Melanesia",
    "region-code": "009",
    "sub-region-code": "054",
  },
  {
    label: "Paraguay",
    value: "Paraguay",
    code: "PY",
    "alpha-2": "PY",
    "alpha-3": "PRY",
    "country-code": "600",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Peru",
    value: "Peru",
    code: "PE",
    "alpha-2": "PE",
    "alpha-3": "PER",
    "country-code": "604",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Philippines",
    value: "Philippines",
    code: "PH",
    "alpha-2": "PH",
    "alpha-3": "PHL",
    "country-code": "608",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Pitcairn",
    value: "Pitcairn",
    code: "PN",
    "alpha-2": "PN",
    "alpha-3": "PCN",
    "country-code": "612",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Poland",
    value: "Poland",
    code: "PL",
    "alpha-2": "PL",
    "alpha-3": "POL",
    "country-code": "616",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Portugal",
    value: "Portugal",
    code: "PT",
    "alpha-2": "PT",
    "alpha-3": "PRT",
    "country-code": "620",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Puerto Rico",
    value: "Puerto Rico",
    code: "PR",
    "alpha-2": "PR",
    "alpha-3": "PRI",
    "country-code": "630",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Qatar",
    value: "Qatar",
    code: "QA",
    "alpha-2": "QA",
    "alpha-3": "QAT",
    "country-code": "634",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Réunion",
    value: "Réunion",
    code: "RE",
    "alpha-2": "RE",
    "alpha-3": "REU",
    "country-code": "638",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Romania",
    value: "Romania",
    code: "RO",
    "alpha-2": "RO",
    "alpha-3": "ROU",
    "country-code": "642",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Russian Federation",
    value: "Russian Federation",
    code: "RU",
    "alpha-2": "RU",
    "alpha-3": "RUS",
    "country-code": "643",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Rwanda",
    value: "Rwanda",
    code: "RW",
    "alpha-2": "RW",
    "alpha-3": "RWA",
    "country-code": "646",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Saint Barthélemy",
    value: "Saint Barthélemy",
    code: "BL",
    "alpha-2": "BL",
    "alpha-3": "BLM",
    "country-code": "652",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    value: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    "alpha-2": "SH",
    "alpha-3": "SHN",
    "country-code": "654",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Saint Kitts and Nevis",
    value: "Saint Kitts and Nevis",
    code: "KN",
    "alpha-2": "KN",
    "alpha-3": "KNA",
    "country-code": "659",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Saint Lucia",
    value: "Saint Lucia",
    code: "LC",
    "alpha-2": "LC",
    "alpha-3": "LCA",
    "country-code": "662",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Saint Martin (French part)",
    value: "Saint Martin (French part)",
    code: "MF",
    "alpha-2": "MF",
    "alpha-3": "MAF",
    "country-code": "663",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Saint Pierre and Miquelon",
    value: "Saint Pierre and Miquelon",
    code: "PM",
    "alpha-2": "PM",
    "alpha-3": "SPM",
    "country-code": "666",
    region: "Americas",
    "sub-region": "Northern America",
    "region-code": "019",
    "sub-region-code": "021",
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
    code: "VC",
    "alpha-2": "VC",
    "alpha-3": "VCT",
    "country-code": "670",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Samoa",
    value: "Samoa",
    code: "WS",
    "alpha-2": "WS",
    "alpha-3": "WSM",
    "country-code": "882",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "San Marino",
    value: "San Marino",
    code: "SM",
    "alpha-2": "SM",
    "alpha-3": "SMR",
    "country-code": "674",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Sao Tome and Principe",
    value: "Sao Tome and Principe",
    code: "ST",
    "alpha-2": "ST",
    "alpha-3": "STP",
    "country-code": "678",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Saudi Arabia",
    value: "Saudi Arabia",
    code: "SA",
    "alpha-2": "SA",
    "alpha-3": "SAU",
    "country-code": "682",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Senegal",
    value: "Senegal",
    code: "SN",
    "alpha-2": "SN",
    "alpha-3": "SEN",
    "country-code": "686",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Serbia",
    value: "Serbia",
    code: "RS",
    "alpha-2": "RS",
    "alpha-3": "SRB",
    "country-code": "688",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Seychelles",
    value: "Seychelles",
    code: "SC",
    "alpha-2": "SC",
    "alpha-3": "SYC",
    "country-code": "690",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Sierra Leone",
    value: "Sierra Leone",
    code: "SL",
    "alpha-2": "SL",
    "alpha-3": "SLE",
    "country-code": "694",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Singapore",
    value: "Singapore",
    code: "SG",
    "alpha-2": "SG",
    "alpha-3": "SGP",
    "country-code": "702",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Sint Maarten (Dutch part)",
    value: "Sint Maarten (Dutch part)",
    code: "SX",
    "alpha-2": "SX",
    "alpha-3": "SXM",
    "country-code": "534",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Slovakia",
    value: "Slovakia",
    code: "SK",
    "alpha-2": "SK",
    "alpha-3": "SVK",
    "country-code": "703",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "Slovenia",
    value: "Slovenia",
    code: "SI",
    "alpha-2": "SI",
    "alpha-3": "SVN",
    "country-code": "705",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Solomon Islands",
    value: "Solomon Islands",
    code: "SB",
    "alpha-2": "SB",
    "alpha-3": "SLB",
    "country-code": "090",
    region: "Oceania",
    "sub-region": "Melanesia",
    "region-code": "009",
    "sub-region-code": "054",
  },
  {
    label: "Somalia",
    value: "Somalia",
    code: "SO",
    "alpha-2": "SO",
    "alpha-3": "SOM",
    "country-code": "706",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "South Africa",
    value: "South Africa",
    code: "ZA",
    "alpha-2": "ZA",
    "alpha-3": "ZAF",
    "country-code": "710",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "South Georgia and the South Sandwich Islands",
    value: "South Georgia and the South Sandwich Islands",
    code: "GS",
    "alpha-2": "GS",
    "alpha-3": "SGS",
    "country-code": "239",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "South Sudan",
    value: "South Sudan",
    code: "SS",
    "alpha-2": "SS",
    "alpha-3": "SSD",
    "country-code": "728",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Spain",
    value: "Spain",
    code: "ES",
    "alpha-2": "ES",
    "alpha-3": "ESP",
    "country-code": "724",
    region: "Europe",
    "sub-region": "Southern Europe",
    "region-code": "150",
    "sub-region-code": "039",
  },
  {
    label: "Sri Lanka",
    value: "Sri Lanka",
    code: "LK",
    "alpha-2": "LK",
    "alpha-3": "LKA",
    "country-code": "144",
    region: "Asia",
    "sub-region": "Southern Asia",
    "region-code": "142",
    "sub-region-code": "034",
  },
  {
    label: "Sudan",
    value: "Sudan",
    code: "SD",
    "alpha-2": "SD",
    "alpha-3": "SDN",
    "country-code": "729",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "Suriname",
    value: "Suriname",
    code: "SR",
    "alpha-2": "SR",
    "alpha-3": "SUR",
    "country-code": "740",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Svalbard and Jan Mayen",
    value: "Svalbard and Jan Mayen",
    code: "SJ",
    "alpha-2": "SJ",
    "alpha-3": "SJM",
    "country-code": "744",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Sweden",
    value: "Sweden",
    code: "SE",
    "alpha-2": "SE",
    "alpha-3": "SWE",
    "country-code": "752",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "Switzerland",
    value: "Switzerland",
    code: "CH",
    "alpha-2": "CH",
    "alpha-3": "CHE",
    "country-code": "756",
    region: "Europe",
    "sub-region": "Western Europe",
    "region-code": "150",
    "sub-region-code": "155",
  },
  {
    label: "Syrian Arab Republic",
    value: "Syrian Arab Republic",
    code: "SY",
    "alpha-2": "SY",
    "alpha-3": "SYR",
    "country-code": "760",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Taiwan, Province of China",
    value: "Taiwan, Province of China",
    code: "TW",
    "alpha-2": "TW",
    "alpha-3": "TWN",
    "country-code": "158",
    region: "Asia",
    "sub-region": "Eastern Asia",
    "region-code": "142",
    "sub-region-code": "030",
  },
  {
    label: "Tajikistan",
    value: "Tajikistan",
    code: "TJ",
    "alpha-2": "TJ",
    "alpha-3": "TJK",
    "country-code": "762",
    region: "Asia",
    "sub-region": "Central Asia",
    "region-code": "142",
    "sub-region-code": "143",
  },
  {
    label: "Tanzania, United Republic of",
    value: "Tanzania, United Republic of",
    code: "TZ",
    "alpha-2": "TZ",
    "alpha-3": "TZA",
    "country-code": "834",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Thailand",
    value: "Thailand",
    code: "TH",
    "alpha-2": "TH",
    "alpha-3": "THA",
    "country-code": "764",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Timor-Leste",
    value: "Timor-Leste",
    code: "TL",
    "alpha-2": "TL",
    "alpha-3": "TLS",
    "country-code": "626",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Togo",
    value: "Togo",
    code: "TG",
    "alpha-2": "TG",
    "alpha-3": "TGO",
    "country-code": "768",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Tokelau",
    value: "Tokelau",
    code: "TK",
    "alpha-2": "TK",
    "alpha-3": "TKL",
    "country-code": "772",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Tonga",
    value: "Tonga",
    code: "TO",
    "alpha-2": "TO",
    "alpha-3": "TON",
    "country-code": "776",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Trinidad and Tobago",
    value: "Trinidad and Tobago",
    code: "TT",
    "alpha-2": "TT",
    "alpha-3": "TTO",
    "country-code": "780",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Tunisia",
    value: "Tunisia",
    code: "TN",
    "alpha-2": "TN",
    "alpha-3": "TUN",
    "country-code": "788",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "Turkey",
    value: "Turkey",
    code: "TR",
    "alpha-2": "TR",
    "alpha-3": "TUR",
    "country-code": "792",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Turkmenistan",
    value: "Turkmenistan",
    code: "TM",
    "alpha-2": "TM",
    "alpha-3": "TKM",
    "country-code": "795",
    region: "Asia",
    "sub-region": "Central Asia",
    "region-code": "142",
    "sub-region-code": "143",
  },
  {
    label: "Turks and Caicos Islands",
    value: "Turks and Caicos Islands",
    code: "TC",
    "alpha-2": "TC",
    "alpha-3": "TCA",
    "country-code": "796",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Tuvalu",
    value: "Tuvalu",
    code: "TV",
    "alpha-2": "TV",
    "alpha-3": "TUV",
    "country-code": "798",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Uganda",
    value: "Uganda",
    code: "UG",
    "alpha-2": "UG",
    "alpha-3": "UGA",
    "country-code": "800",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Ukraine",
    value: "Ukraine",
    code: "UA",
    "alpha-2": "UA",
    "alpha-3": "UKR",
    "country-code": "804",
    region: "Europe",
    "sub-region": "Eastern Europe",
    "region-code": "150",
    "sub-region-code": "151",
  },
  {
    label: "United Arab Emirates",
    value: "United Arab Emirates",
    code: "AE",
    "alpha-2": "AE",
    "alpha-3": "ARE",
    "country-code": "784",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "United Kingdom of Great Britain and Northern Ireland",
    value: "United Kingdom of Great Britain and Northern Ireland",
    code: "GB",
    "alpha-2": "GB",
    "alpha-3": "GBR",
    "country-code": "826",
    region: "Europe",
    "sub-region": "Northern Europe",
    "region-code": "150",
    "sub-region-code": "154",
  },
  {
    label: "United States of America",
    value: "United States of America",
    code: "US",
    "alpha-2": "US",
    "alpha-3": "USA",
    "country-code": "840",
    region: "Americas",
    "sub-region": "Northern America",
    "region-code": "019",
    "sub-region-code": "021",
  },
  {
    label: "United States Minor Outlying Islands",
    value: "United States Minor Outlying Islands",
    code: "UM",
    "alpha-2": "UM",
    "alpha-3": "UMI",
    "country-code": "581",
    region: "Oceania",
    "sub-region": "Micronesia",
    "region-code": "009",
    "sub-region-code": "057",
  },
  {
    label: "Uruguay",
    value: "Uruguay",
    code: "UY",
    "alpha-2": "UY",
    "alpha-3": "URY",
    "country-code": "858",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Uzbekistan",
    value: "Uzbekistan",
    code: "UZ",
    "alpha-2": "UZ",
    "alpha-3": "UZB",
    "country-code": "860",
    region: "Asia",
    "sub-region": "Central Asia",
    "region-code": "142",
    "sub-region-code": "143",
  },
  {
    label: "Vanuatu",
    value: "Vanuatu",
    code: "VU",
    "alpha-2": "VU",
    "alpha-3": "VUT",
    "country-code": "548",
    region: "Oceania",
    "sub-region": "Melanesia",
    "region-code": "009",
    "sub-region-code": "054",
  },
  {
    label: "Venezuela (Bolivarian Republic of)",
    value: "Venezuela (Bolivarian Republic of)",
    code: "VE",
    "alpha-2": "VE",
    "alpha-3": "VEN",
    "country-code": "862",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Viet Nam",
    value: "Viet Nam",
    code: "VN",
    "alpha-2": "VN",
    "alpha-3": "VNM",
    "country-code": "704",
    region: "Asia",
    "sub-region": "South-eastern Asia",
    "region-code": "142",
    "sub-region-code": "035",
  },
  {
    label: "Virgin Islands (British)",
    value: "Virgin Islands (British)",
    code: "VG",
    "alpha-2": "VG",
    "alpha-3": "VGB",
    "country-code": "092",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Virgin Islands (U.S.)",
    value: "Virgin Islands (U.S.)",
    code: "VI",
    "alpha-2": "VI",
    "alpha-3": "VIR",
    "country-code": "850",
    region: "Americas",
    "sub-region": "Latin America and the Caribbean",
    "region-code": "019",
    "sub-region-code": "419",
  },
  {
    label: "Wallis and Futuna",
    value: "Wallis and Futuna",
    code: "WF",
    "alpha-2": "WF",
    "alpha-3": "WLF",
    "country-code": "876",
    region: "Oceania",
    "sub-region": "Polynesia",
    "region-code": "009",
    "sub-region-code": "061",
  },
  {
    label: "Western Sahara",
    value: "Western Sahara",
    code: "EH",
    "alpha-2": "EH",
    "alpha-3": "ESH",
    "country-code": "732",
    region: "Africa",
    "sub-region": "Northern Africa",
    "region-code": "002",
    "sub-region-code": "015",
  },
  {
    label: "Yemen",
    value: "Yemen",
    code: "YE",
    "alpha-2": "YE",
    "alpha-3": "YEM",
    "country-code": "887",
    region: "Asia",
    "sub-region": "Western Asia",
    "region-code": "142",
    "sub-region-code": "145",
  },
  {
    label: "Zambia",
    value: "Zambia",
    code: "ZM",
    "alpha-2": "ZM",
    "alpha-3": "ZMB",
    "country-code": "894",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
  {
    label: "Zimbabwe",
    value: "Zimbabwe",
    code: "ZW",
    "alpha-2": "ZW",
    "alpha-3": "ZWE",
    "country-code": "716",
    region: "Africa",
    "sub-region": "Sub-Saharan Africa",
    "region-code": "002",
    "sub-region-code": "202",
  },
];
